global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'mcp-server'
    metrics_path: /metrics
    static_configs:
      - targets: ['mcp-server:8000']

  - job_name: 'neo4j'
    metrics_path: /metrics
    static_configs:
      - targets: ['neo4j:2004']

  - job_name: 'qdrant'
    metrics_path: /metrics
    static_configs:
      - targets: ['qdrant:6333']